---

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: reload systemd
  become: yes
  command: >
    systemctl daemon-reload

- name: restart systemd-journald
  service:
    name: systemd-journald
    state: restarted

