---

- name: install dependancies
  become: yes
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - python-setuptools
    - java-1.8.0-openjdk-headless

- name: ensure elasticsearch and curator repositories are added
  become: yes
  copy:
    src: "{{item}}"
    dest: /etc/yum.repos.d/{{item}}
    mode: 0644
  with_items:
    - elasticsearch.repo
    - curator.repo
  tags:
    - curator

- name: install packages
  become: yes
  package:
    name: "{{item}}"
    state: present
  with_items:
    - elasticsearch-{{elasticsearch_version}}
    - elasticsearch-curator-{{elasticsearch_curator_version}}
  tags:
    - curator

- name: ensure elasticsearch systemd unit is up to date
  become: yes
  template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service
    mode: 0644
  register: units

- name: reload units
  become: yes
  shell: systemctl daemon-reload
  when: units | changed

- name: ensure elasticsearch sysconfig is deployed
  become: yes
  template:
    src: sysconfig-elasticsearch.j2
    dest: /etc/sysconfig/elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: ensure directories exist
  become: yes
  file:
    path: "{{item}}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
  with_items:
    - "{{elasticsearch_home_dir}}"
    - "{{elasticsearch_root_dir}}"
    - "{{elasticsearch_conf_dir}}"
    - "{{elasticsearch_cert_dir}}"
    - "{{elasticsearch_data_dir}}"
    - "{{elasticsearch_log_dir}}"
    - "{{elasticsearch_work_dir}}"
    - "{{elasticsearch_plugin_dir}}"

- name: ensure elasticsearch config is deployed
  become: yes
  template:
    src={{item}}.j2
    dest="{{elasticsearch_conf_dir}}/{{item}}"
    owner=elasticsearch
    group=elasticsearch
    mode=0644
  with_items:
    - elasticsearch.yml
    - jvm.options
  tags: quick
  notify: restart elasticsearch

- name: ensure elasticsearch service is enabled and started
  become: yes
  service:
    name: elasticsearch
    enabled: yes
    state: started

- name: ensure elasticsearch info tool is deployed
  copy:
    src: esinfo
    dest: /bin/esinfo
    mode: 0750

